#!/bin/bash
# Test all 24 secret codes to verify they work correctly
# This script opens the assessment and provides instructions for manual testing

echo "=========================================="
echo "STTI Assessment Secret Code Test Protocol"
echo "=========================================="
echo ""
echo "Opening assessment in browser..."
echo ""

# Open the assessment
open "/Users/nick/Dropbox/+/AI/Efforts/Active/STTI Assessment Dev/Web-App/index.html"

sleep 2

echo "✅ Assessment opened"
echo ""
echo "MANUAL TEST INSTRUCTIONS:"
echo "========================="
echo ""
echo "Test each secret code by typing the 4-digit code:"
echo ""
echo "GROUP 1 - CONVERTERS:"
echo "  0001 → IP-Architect (The Converter)"
echo "  0002 → IP-Gardener (The Converter)"
echo "  0007 → PI-Architect (The Converter)"
echo "  0008 → PI-Gardener (The Converter)"
echo ""
echo "GROUP 2 - PHILOSOPHERS:"
echo "  0003 → IS-Architect (The Philosopher)"
echo "  0004 → IS-Gardener (The Philosopher)"
echo "  0013 → SI-Architect (The Philosopher)"
echo "  0014 → SI-Gardener (The Philosopher)"
echo ""
echo "GROUP 3 - EXPLORERS:"
echo "  0005 → IC-Architect (The Explorer)"
echo "  0006 → IC-Gardener (The Explorer)"
echo "  0019 → CI-Architect (The Explorer)"
echo "  0020 → CI-Gardener (The Explorer)"
echo ""
echo "GROUP 4 - BUILDERS:"
echo "  0009 → PS-Architect (The Builder)"
echo "  0010 → PS-Gardener (The Builder)"
echo "  0015 → SP-Architect (The Builder)"
echo "  0016 → SP-Gardener (The Builder)"
echo ""
echo "GROUP 5 - MAKERS:"
echo "  0011 → PC-Architect (The Maker)"
echo "  0012 → PC-Gardener (The Maker)"
echo "  0021 → CP-Architect (The Maker)"
echo "  0022 → CP-Gardener (The Maker)"
echo ""
echo "GROUP 6 - TRANSLATORS:"
echo "  0017 → SC-Architect (The Translator)"
echo "  0018 → SC-Gardener (The Translator)"
echo "  0023 → CS-Architect (The Translator)"
echo "  0024 → CS-Gardener (The Translator)"
echo ""
echo "WHAT TO CHECK FOR EACH CODE:"
echo "============================"
echo "✓ Profile code displays correctly (e.g., 'IP-Architect')"
echo "✓ Subtitle displays correctly (e.g., 'The Converter')"
echo "✓ Chord diagram loads (image shows)"
echo "✓ Archetype pills show (4 pills with correct colors)"
echo "✓ Tendency pills show (primary + secondary)"
echo "✓ Orientation pill shows"
echo "✓ Three descriptions display (archetype, orientation, tendency)"
echo "✓ Three collapsible sections appear (overwhelmed, stuck/unstuck, prompts)"
echo "✓ Sections contain profile-specific content (not generic placeholders)"
echo "✓ No console errors (open DevTools with Cmd+Option+I)"
echo ""
echo "PRIORITY PROFILES TO TEST:"
echo "=========================="
echo "  0001 (IP-Architect) - First in list"
echo "  0003 (IS-Architect) - Default test profile"
echo "  0012 (PC-Gardener) - Mid-range"
echo "  0024 (CS-Gardener) - Last in list"
echo ""
echo "Press Enter when testing is complete..."
read

echo ""
echo "Did all secret codes work correctly? (y/n)"
read response

if [ "$response" = "y" ] || [ "$response" = "Y" ]; then
    echo "✅ SECRET CODE TEST: PASSED"
    echo ""
    echo "All 24 profiles are working correctly!"
    exit 0
else
    echo "❌ SECRET CODE TEST: FAILED"
    echo ""
    echo "Please note which codes failed and report the issues."
    exit 1
fi
